// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbQRipVANe52xC1hepeJJ5ZmDlDf_Ni8w',
    appId: '1:802254302838:web:02b72900c0a63f53963957',
    messagingSenderId: '802254302838',
    projectId: 'chattapp-fee3c',
    authDomain: 'chattapp-fee3c.firebaseapp.com',
    databaseURL: 'https://chattapp-fee3c-default-rtdb.firebaseio.com',
    storageBucket: 'chattapp-fee3c.appspot.com',
    measurementId: 'G-BE50XENQ3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWukDrFWM7ql5TSuFQVzefiZHUnJ3pO_k',
    appId: '1:802254302838:android:6101be7e26a417eb963957',
    messagingSenderId: '802254302838',
    projectId: 'chattapp-fee3c',
    databaseURL: 'https://chattapp-fee3c-default-rtdb.firebaseio.com',
    storageBucket: 'chattapp-fee3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfx9oPNwaEIvV4kVLvFBhhmETiWRDDNpg',
    appId: '1:802254302838:ios:fb2b7a824a729172963957',
    messagingSenderId: '802254302838',
    projectId: 'chattapp-fee3c',
    databaseURL: 'https://chattapp-fee3c-default-rtdb.firebaseio.com',
    storageBucket: 'chattapp-fee3c.appspot.com',
    androidClientId: '802254302838-ha2njva7l7ahf66alqfc6f92oem40bbf.apps.googleusercontent.com',
    iosClientId: '802254302838-2etnht2hvk9qfvq6djcmt8028thjimej.apps.googleusercontent.com',
    iosBundleId: 'com.example.agoraVoiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfx9oPNwaEIvV4kVLvFBhhmETiWRDDNpg',
    appId: '1:802254302838:ios:fb2b7a824a729172963957',
    messagingSenderId: '802254302838',
    projectId: 'chattapp-fee3c',
    databaseURL: 'https://chattapp-fee3c-default-rtdb.firebaseio.com',
    storageBucket: 'chattapp-fee3c.appspot.com',
    androidClientId: '802254302838-ha2njva7l7ahf66alqfc6f92oem40bbf.apps.googleusercontent.com',
    iosClientId: '802254302838-2etnht2hvk9qfvq6djcmt8028thjimej.apps.googleusercontent.com',
    iosBundleId: 'com.example.agoraVoiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbQRipVANe52xC1hepeJJ5ZmDlDf_Ni8w',
    appId: '1:802254302838:web:5d04428890549344963957',
    messagingSenderId: '802254302838',
    projectId: 'chattapp-fee3c',
    authDomain: 'chattapp-fee3c.firebaseapp.com',
    databaseURL: 'https://chattapp-fee3c-default-rtdb.firebaseio.com',
    storageBucket: 'chattapp-fee3c.appspot.com',
    measurementId: 'G-QHCNF9HWKX',
  );
}
